const { Client, LocalAuth } = require("whatsapp-web.js");

const client = new Client({
  restartOnAuthFail: true,
  puppeteer: {
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  },
  authStrategy: new LocalAuth({ clientId: "client" }),
});

client.on("qr", (qr) => {
  console.log("QR RECEIVED", qr);
});

client.on("ready", () => {
  console.log("Client is ready!");
});

client.on("message", async (msg) => {
  const isGroup = msg.from.endsWith("@g.us") ? true : false;
  if (msg._data.caption == "/sticker" && msg.type == "image" && !isGroup) {
    try {
      const media = await msg.downloadMedia();
      client.sendMessage(msg.from, media, {
        sendMediaAsSticker: true,
        stickerName: "generated by skyebot",
        stickerAuthor: "Skye",
      });
    } catch {
      client.sendMessage(msg.from, "gagal ges");
    }
  }
});

client.initialize();
